
line-length = 79
exclude = [".venv/", "tests/", "*/migrations/"]

[lint]
extend-select = ["I", "E", "W", "F"]
ignore = ["F811"]
preview = true

[lint.extend-per-file-ignores]
"settings.py" = ["E501"]

[lint.isort]
combine-as-imports = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "single"
