version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: novahfly/foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media

  frontend:
    image: novahfly/foodgram-frontend
    
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - 8010:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - static:/static
      - media:/media
