# Generated by Django 3.2.16 on 2024-10-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241023_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
    ]
