# Generated by Django 3.2.16 on 2024-10-24 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorited_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorited_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
