# Generated by Django 3.2.16 on 2024-10-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20241029_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
