# Generated by Django 3.2.16 on 2024-11-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_remove_recipe_favorited_by_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
