# Generated by Django 3.2.16 on 2024-10-22 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
