# Generated by Django 3.2.16 on 2024-11-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscriptions',
            options={'ordering': ['user__username'], 'verbose_name': 'Список подписок', 'verbose_name_plural': 'Списки подписок'},
        ),
    ]
