# Generated by Django 3.2.16 on 2024-11-05 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_alter_usersubscriptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
