# Generated by Django 3.2.16 on 2024-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.URLField(unique=True, verbose_name='Полный путь до ресурса')),
                ('short_token', models.CharField(max_length=32, unique=True, verbose_name='Короткий токен')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
                'ordering': ['full_path'],
            },
        ),
    ]
