# Generated by Django 3.2.16 on 2024-11-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='full_path',
            field=models.CharField(max_length=200, unique=True, verbose_name='Полный путь до ресурса'),
        ),
    ]
